config/routes.rb
Rails.application.routes.draw do
  root 'artists#index'

  resources 'artists' do
    resources 'songs', only: [:new, :create, :edit, :update]
  end

  resources 'songs', only: [:show, :index, :destroy]

  resources 'playlists'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :image_path, presence: true

  has_many :songs
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  validates :name, presence: true

  has_many :playlist_songs
  has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :song
  belongs_to :playlist
end

app/models/song.rb
class Song < ApplicationRecord
  validates :title, presence: true
  validates :artist, presence: true
  
  belongs_to :artist
  has_many :playlist_songs
  has_many :playlists, through: :playlist_songs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      flash.notice = "Artist '#{@artist.name}' Created!"
      redirect_to artist_path(@artist)
    else
      @errors = @artist.errors
      render :new
    end
  end

  def show
    @artist = Artist.find(params[:id])
    @songs = @artist.songs
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    if @artist.update(artist_params)
      flash.notice = "Artist '#{@artist.name}' Updated!"
      redirect_to @artist
    else
      @errors = @artist.errors
      render :new
    end
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.delete
    redirect_to artists_path
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :image_path)
  end
  
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  
  def index
    @playlists = Playlist.all
  end

  def new
    @songs = Song.all
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.new(playlist_params)
    if @playlist.save
      flash.notice = "Playlist '#{@playlist.name}' Created!"
      redirect_to playlist_path(@playlist)
    else
      @errors = @playlist.errors
      @songs = Song.all
      render :new
    end
  end

  def show
    @playlist = Playlist.find(params[:id])
  end

  def edit
    @playlist = Playlist.find(params[:id])
    @songs = Song.all
  end

  def update
    @playlist = Playlist.find(params[:id])
    if @playlist.update(playlist_params)
      flash.notice = "Playlist '#{@playlist.name}' Updated!"
      redirect_to playlist_path(@playlist)
    else
      @errors = @playlist.errors
      render :edit
    end
  end

  def destroy
    playlist = Playlist.find(params[:id])
    playlist.delete

    redirect_to playlists_path
  end

  private

  def playlist_params
    params.require(:playlist).permit(:name, song_ids: [])
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def new
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.new
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.new(song_params)
    if @song.save
      flash.notice = "Song '#{@song.title}' Created for #{@artist.name}."
      redirect_to song_path(@song)
    else
      @errors = @song.errors
      render :new
    end
  end

  def show
    @song = Song.find(params[:id])
  end

  def index
    @songs = Song.all.sort_by{|song| song.title}
  end

  def edit
    @song = Song.find(params[:id])
    @artist = Artist.find(params[:artist_id])
  end

  def update
    @song = Song.find(params[:id])
    if @song.update(song_params)
      redirect_to song_path(@song)
    else
      @errors = @song.errors
      render :edit
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @artist = @song.artist
    @song.delete
    redirect_to artist_path(@artist)
  end

  private

  def song_params
    params.require(:song).permit(:title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/_form.html.erb
<div class="container">
  <div class="col-md-6">
    <%= bootstrap_form_for(@artist) do |f| %>
      <%= f.text_field :name %>
      <%= f.text_field :image_path %>
      <%= f.submit nil, :class => 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/artists/edit.html.erb
<h2>Edit <%= @artist.name %></h2>

<%= render partial: "form" %>

app/views/artists/index.html.erb
<h2>All Artists</h2>

<div class="container">
  <div class="col-md-2">
    <ul class="list-group">
    <% @artists.each do |artist| %>
      <%= link_to artist.name, artist, class:"list-group-item" %>
    <% end %>
    </ul>
    <%= link_to "New Artist", new_artist_path, class:"btn btn-primary"%>
  </div>
</div>

<div class="container">
  <br/>
  <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
    <%= link_to "Songs", songs_path, class:"btn btn-info"%>
    <%= link_to "Playlists", playlists_path, class:"btn btn-info"%>
  </div>
</div>

app/views/artists/new.html.erb
<h2>Make a New Artist</h2>

<%= render partial: "form" %>

app/views/artists/show.html.erb
<h2><%= @artist.name %></h2>

<div class="container">
<%= image_tag @artist.image_path %>
</div>

<div class="container">
  <div class="col-md-3">
    <h4>Songs</h4>
    <ul class="list-group">
      <% @songs.each do |song| %>
        <li class="list-group-item"><%= link_to song.title, song_path(song) %></li>
      <% end %>
    </ul>
  </div>
</div>

<div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
  <%= link_to "All Artists", artists_path, class:"btn btn-primary"%>
  <%= link_to "Edit", edit_artist_path(@artist), class:"btn btn-warning"%>
  <%= link_to "Delete", artist_path(@artist), method: :delete, class:"btn btn-danger", data: {confirm: "Are you sure?"}%>
  <%= link_to "New Song", new_artist_song_path(@artist), class:"btn btn-success"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MixMaster</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
    <%= render partial: "shared/errors" %>
    <%= render partial: "shared/flash" %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/playlists/_form.html.erb
<div class="container">
  <div class="col-md-6">
    <%= bootstrap_form_for(@playlist) do |f| %>
      <%= f.text_field :name %>

      <%= f.collection_check_boxes("song_ids", @songs, :id, :title) do |song| %>
        <%= song.title { song.check_box } %>
      <% end %>

      <%= f.submit nil, :class => 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/playlists/edit.html.erb
<h2>Edit Playlist</h2>

<%= render partial: "form" %>

app/views/playlists/index.html.erb
<h2>All Playlists</h2>

<div class="container">
  <div class="col-md-2">
    <ul class="list-group">
    <% @playlists.each do |playlist| %>
      <%= link_to playlist.name, playlist_path(playlist), class:"list-group-item" %>
    <% end %>
    </ul>
    <%= link_to "New Playlist", new_playlist_path, class:"btn btn-primary"%>
  </div>
</div>


<div class="container">
  <br/>
  <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
    <%= link_to "Artists", artists_path, class:"btn btn-info"%>
    <%= link_to "Songs", songs_path, class:"btn btn-info"%>
  </div>
</div>

app/views/playlists/new.html.erb
<h2>Make a New Playlist</h2>

<%= render partial: "form" %>

app/views/playlists/show.html.erb
<h2><%= @playlist.name %></h2>

<div class="container">
  <div class="col-md-6">
    <ul class="list-group">
      <% @playlist.songs.each do |song| %>
        <li class="list-group-item"><%= link_to song.title, song_path(song) %></li>
      <% end %>
    </ul>
  </div>
</div>

<div class="container">
  <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
    <%= link_to "Edit", edit_playlist_path(@playlist), class:"btn btn-warning"%>
    <%= link_to "Delete", playlist_path(@playlist), method: :delete, class:"btn btn-danger", data: {confirm: "Are you sure?"}%>
    <%= link_to "All Playlists", playlists_path, class:"btn btn-primary"%>
  </div>
</div>

app/views/shared/_errors.html.erb
 
 <% if @errors %>
   <div class="alert alert-danger">
    <h4><%= pluralize(@errors.count, "error") %> prohibited this record from being saved:</h4>
    <ul>
      <% @errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    </div>
  <% end %>

app/views/shared/_flash.html.erb
<% if flash.notice %>
  <p class="alert alert-success"> <%= flash.notice %> </p>
<% end %>

app/views/songs/_form.html.erb
<div class="container">
  <div class="col-md-6">
    <%= bootstrap_form_for([@artist, @song]) do |f| %>
      <%= f.text_field :title %>
      <%= f.submit nil, :class => 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/songs/edit.html.erb
<h4>Update Song</h4>

<%= render partial: "form" %>

app/views/songs/index.html.erb
<h2>All Songs</h2>

<div class="container">
  <div class="col-md-2">
    <ul class="list-group">
    <% @songs.each do |song| %>
      <%= link_to song.title, song_path(song), class:"list-group-item" %>
    <% end %>
    </ul>
  </div>
</div>

<div class="container">
  <br/>
  <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
    <%= link_to "Artists", artists_path, class:"btn btn-info"%>
    <%= link_to "Playlists", playlists_path, class:"btn btn-info"%>
  </div>
</div>

app/views/songs/new.html.erb
<h4>Enter a New Song for <%= @artist.name%></h4>

<%= render partial: "form" %>

app/views/songs/show.html.erb
<h2>Song: <%= @song.title %></h2>
<h2>Artist: <%= link_to @song.artist.name, artist_path(@song.artist) %></h2>

<div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
  <%= link_to "All Songs", songs_path, class:"btn btn-primary"%>
  <%= link_to "Edit", edit_artist_song_path(@song.artist, @song), class:"btn btn-warning"%>
  <%= link_to "Delete", song_path(@song), method: :delete, class:"btn btn-danger", data: {confirm: "Are you sure?"}%>
  <%= link_to @song.artist.name, artist_path(@song.artist), class:"btn btn-success"%>
</div>